<?php

/**
 * @file
 * Primary module hooks for Rezultati module.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view().
 */
function rezultati_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode): void {
  if ($entity->bundle() == 'igralka') {
    $references = 'tocke 123';

    $build['custom_reference_count'] = [
      '#markup' => '<div class="field field-name-custom-reference-count">Number of References: ' . $references . '</div>',
    ];
  }
}

/**
 * Implements hook_entity_extra_field_info().ddev start
 */
function rezultati_entity_extra_field_info() {
  $extra['node']['igralka']['display']['tocke'] = [
    'label' => t('Tocke'),
    'description' => t('Displays the number of references in the reference field.'),
    'weight' => 0,
  ];

  return $extra;
}
