<?php

/**
 * @file
 * Primary module hooks for Rezultati module.
 */

/**
 * Implements hook_form_alter().
 */
function rezultati_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_rezultat_form') {
    $form['title']['widget'][0]['value']['#default_value'] = 'Punce rezultat';
    $form['title']['#access'] = FALSE;
  }
}

/**
 * Implements hook_entity_insert().
 */
function rezultati_entity_insert(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->bundle() === 'rezultat') {
    $tocke = Drupal::service('rezultati.tocke')->calculatePoints();
  }
}

/**
 * Implements hook_entity_delete().
 */
function rezultati_entity_delete(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->bundle() === 'rezultat') {
    $tocke = Drupal::service('rezultati.tocke')->calculatePoints();
  }
}
